# Generated by Django 5.2.5 on 2025-08-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_rename_timestamp_ticket_created_at_ticket_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
